---

- hosts: all
  become: yes

  vars:

    rsyslog_log_put_body: >-
      {
          "template": "log-*",
          "settings": {
            "number_of_shards": 1
          },
          "mappings": {
              "event": {
                  "properties": {
                      "timestamp": {
                          "type": "date"
                      },
                      "host": {
                          "type": "string",
                          "index": "not_analyzed"
                      },
                      "syslogtag": {
                          "type": "string",
                          "index": "not_analyzed"
                      },
                      "programname": {
                          "type": "string",
                          "index": "not_analyzed"
                      },
                      "severity": {
                          "type": "string",
                          "index": "not_analyzed"
                      },
                      "facility": {
                          "type": "string",
                          "index": "not_analyzed"
                      },
                      "message": {
                          "type": "string"
                      }
                  }
              }
          }
      }

    logstash_log_put_body: >-
      {
          "template": "logstash-*",
          "settings": {
              "number_of_shards": 1
          },
          "mappings": {
              "logs": {
                  "properties": {
                      "@timestamp": {
                          "type": "date"
                      },
                      "timestamp": {
                          "type": "string",
                          "index": "not_analyzed"
                      },
                      "host": {
                          "type": "string",
                          "index": "not_analyzed"
                      },
                      "logsource": {
                          "type": "string",
                          "index": "not_analyzed"
                      },
                      "program": {
                          "type": "string",
                          "index": "not_analyzed"
                      },
                      "facility": {
                          "type": "long"
                      }
                      "facility_label": {
                          "type": "string",
                          "index": "not_analyzed"
                      },
                      "severity": {
                          "type": "long"
                      }
                      "severity_label": {
                          "type": "string",
                          "index": "not_analyzed"
                      },
                      "pid": {
                          "type": "string",
                          "index": "not_analyzed"
                      },
                      "@version": {
                          "type": "string",
                          "index": "not_analyzed"
                      },
                      "filename": {
                          "type": "string"
                      }
                  }
              }
          }
      }

  tasks:

    - name: Install Java 7 runtime
      apt:
        pkg: openjdk-7-jre
        state: present
        update_cache: yes

    - name: Check whether Elasticsearch is installed
      command: dpkg -s elasticsearch
      register: es_dpkg_test
      ignore_errors: yes

    - name: Download Elasticsearch package
      get_url:
        url: https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.3.3/elasticsearch-2.3.3.deb
        dest: /tmp/elasticsearch-2.3.3.deb
      when: es_dpkg_test.rc != 0
      # In production, we'd want to check the installed version number and
      # remove an old version if it exists.

    - name: Remove old Elasticsearch package
      command: dpkg --remove elasticsearch
      when: es_dpkg_test.rc != 0

    - name: Install Elasticsearch package
      command: dpkg -i -E --force-confnew /tmp/elasticsearch-2.3.3.deb
      when: es_dpkg_test.rc != 0
      notify: restart elasticsearch

    - name: Ensure init script run levels
      command: update-rc.d elasticsearch defaults

    - name: Ensure state of Elasticsearch config file
      template:
        src: templates/elasticsearch.yml.j2
        dest: /etc/elasticsearch/elasticsearch.yml
      notify: restart elasticsearch

    - meta: flush_handlers

    - name: Wait for Elasticsearch to respond
      local_action: wait_for host=localhost port=9200 delay=10 timeout=60
      become: no

    - name: Set Elasticsearch Index Template (direct Rsyslog index)
      local_action: >-
        command curl -X PUT "http://localhost:9200/_template/rsysloglogs"
                     -d '{{ rsyslog_log_put_body }}'
      become: no

    - name: Set Elasticsearch Index Template (Logstash index)
      local_action: >-
        command curl -X PUT "http://localhost:9200/_template/logstashlogs"
                     -d '{{ logstash_log_put_body }}'
      become: no

  handlers:
    - name: restart elasticsearch
      service: name=elasticsearch state=restarted

- hosts: all
  become: yes

  tasks:

    - name: Add Adiscon repository for rsyslog
      apt_repository: repo='ppa:adiscon/v8-stable'

    - name: Ensure that rsyslog and its ES plugin are installed
      apt: >-
        pkg="{{ item }}" state=latest update_cache=yes force=yes
      with_items:
        - rsyslog
        - rsyslog-elasticsearch
      notify: restart rsyslog

    - name: Ensure state of rsyslog main config file
      template:
        src: files/rsyslog.conf
        dest: /etc/rsyslog.conf
      notify: restart rsyslog

    - name: Ensure state of rsyslog default configuration file
      template:
        src: templates/50-default.conf.j2
        dest: /etc/rsyslog.d/50-default.conf
      notify: restart rsyslog

    - name: Ensure state of rsyslog elasticsearch module file
      template:
        src: templates/55-elasticsearch.conf.j2
        dest: /etc/rsyslog.d/55-elasticsearch.conf
      notify: restart rsyslog

    - name: Ensure that unneeded packages are absent
      apt: >-
        pkg="{{ item }}" state=absent purge=yes
      with_items:
        - puppet
        - pppoeconf
        - ppp
        - chef

  handlers:
    - name: restart rsyslog
      service: name=rsyslog state=restarted

- hosts: all
  become: yes
  tasks:

    - name: Check whether Kibana is installed
      command: dpkg -s kibana
      register: k_dpkg_test
      ignore_errors: yes

    - name: Download Kibana package
      get_url:
        url: https://download.elastic.co/kibana/kibana/kibana_4.5.1_amd64.deb
        dest: /tmp/kibana_4.5.1_amd64.deb
      when: k_dpkg_test.rc != 0

    - name: Install Kibana package
      command: dpkg -i -E --force-confnew /tmp/kibana_4.5.1_amd64.deb
      when: k_dpkg_test.rc != 0
      notify: restart kibana

    - name: Ensure init script run levels
      command: update-rc.d kibana defaults

    - name: Ensure state of Kibana config file
      template:
        src: templates/kibana.yml.j2
        dest: /opt/kibana/config/kibana.yml
      notify: restart kibana

  handlers:
    - name: restart kibana
      service: name=kibana state=restarted

# You should now be able to see Kibana at http://localhost:5601/

- hosts: all
  become: yes
  tasks:

    - name: Add Logstash APT repository
      apt_repository:
        repo: 'deb https://packages.elastic.co/logstash/2.4/debian stable main'

    - name: Ensure that Logstash is installed
      apt: pkg=logstash state=present update_cache=yes force=yes
      notify: restart logstash

    - name: Ensure state of syslog pipeline config file
      template:
        src: templates/syslog-pipeline.conf.j2
        dest: /etc/logstash/conf.d/syslog-pipeline.conf
      notify: restart logstash
      tags:
        - pipeline

  handlers:
    - name: restart logstash
      service: name=logstash state=restarted

# Now with that Logstash setup, you should be able to use a utility like
# `logger(1)' to send a syslog message from your host environment to your
# VM, so that it gets parsed and inserted into Elasticsearch for Kibana to find.
# Example, on my host:
# $ logger -s -r 192.168.50.20 -l local0.info "Test message"
